"""Initial Migration

Revision ID: 010c56d65fbe
Revises: 61a7486dd93e
Create Date: 2018-10-23 21:57:15.004131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010c56d65fbe'
down_revision = '61a7486dd93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_blog_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_blog_fkey', 'comments', 'blogs', ['blog'], ['id'])
    # ### end Alembic commands ###
